import Foundation

public enum DependencyType: String, CaseIterable, Identifiable, Sendable {
    case nodeModules = "node_modules"
    case pythonVenv = ".venv"
    case pythonVenvAlt = "venv"
    case pythonEnv = "env"
    case dist = "dist"
    case build = "build"
    case nextjs = ".next"
    case nuxtjs = ".nuxt"
    case target = "target"
    case pods = "Pods"
    case pycache = "__pycache__"
    case gradle = ".gradle"
    case vendor = "vendor"
    case dartTool = ".dart_tool"
    case pubCache = ".pub-cache"
    case dotCache = ".cache"
    case swiftBuild = ".build"
    case pytestCache = ".pytest_cache"
    case mypyCache = ".mypy_cache"
    case ruffCache = ".ruff_cache"
    case tox = ".tox"
    case turbo = ".turbo"
    case parcelCache = ".parcel-cache"
    case svelteKit = ".svelte-kit"
    case angularCache = ".angular"
    case yarnCache = ".yarn"
    case pnpmStore = ".pnpm-store"
    case swiftPM = ".swiftpm"
    case history = ".history"
    case fsCache = ".fs_cache"
    case coverage = "coverage"
    case out = "out"
    case bin = "bin"
    case obj = "obj"
    case release = "release"
    case libraryCaches = "Library/Caches"
    case derivedData = "DerivedData"
    case cmakeBuildDebug = "cmake-build-debug"
    case cmakeBuildRelease = "cmake-build-release"
    case cmakeBuild = "cmake-build"
    case carthageBuild = "Carthage/Build"
    case bazelBin = "bazel-bin"
    case bazelOut = "bazel-out"
    case bazelTestlogs = "bazel-testlogs"
    case cxx = ".cxx"
    case externalNativeBuild = ".externalNativeBuild"
    case kotlinCache = ".kotlin"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .nodeModules: return "node_modules (Node.js)"
        case .pythonVenv: return ".venv (Python)"
        case .pythonVenvAlt: return "venv (Python)"
        case .pythonEnv: return "env (Python)"
        case .dist: return "dist (构建产物)"
        case .build: return "build (构建产物)"
        case .nextjs: return ".next (Next.js)"
        case .nuxtjs: return ".nuxt (Nuxt.js)"
        case .target: return "target (Rust/Java)"
        case .pods: return "Pods (CocoaPods)"
        case .pycache: return "__pycache__ (Python)"
        case .gradle: return ".gradle (Gradle)"
        case .vendor: return "vendor (Go/PHP)"
        case .dartTool: return ".dart_tool (Dart)"
        case .pubCache: return ".pub-cache (Dart/Flutter)"
        case .dotCache: return ".cache (缓存)"
        case .swiftBuild: return ".build (Swift 编译产物)"
        case .pytestCache: return ".pytest_cache (pytest 缓存)"
        case .mypyCache: return ".mypy_cache (mypy 缓存)"
        case .ruffCache: return ".ruff_cache (Ruff 缓存)"
        case .tox: return ".tox (Python 测试环境)"
        case .turbo: return ".turbo (Turborepo 缓存)"
        case .parcelCache: return ".parcel-cache (Parcel 缓存)"
        case .svelteKit: return ".svelte-kit (SvelteKit 产物)"
        case .angularCache: return ".angular (Angular 缓存)"
        case .yarnCache: return ".yarn (Yarn 缓存)"
        case .pnpmStore: return ".pnpm-store (pnpm 缓存)"
        case .swiftPM: return ".swiftpm (SwiftPM 缓存)"
        case .history: return ".history (历史快照)"
        case .fsCache: return ".fs_cache (应用缓存)"
        case .coverage: return "coverage (测试覆盖率)"
        case .out: return "out (构建产物)"
        case .bin: return "bin (构建产物)"
        case .obj: return "obj (构建产物)"
        case .release: return "release (发布产物)"
        case .libraryCaches: return "Library/Caches (开发缓存)"
        case .derivedData: return "DerivedData (Xcode 产物)"
        case .cmakeBuildDebug: return "cmake-build-debug (CMake 产物)"
        case .cmakeBuildRelease: return "cmake-build-release (CMake 产物)"
        case .cmakeBuild: return "cmake-build-* (CMake 产物)"
        case .carthageBuild: return "Carthage/Build (Carthage 产物)"
        case .bazelBin: return "bazel-bin (Bazel 产物)"
        case .bazelOut: return "bazel-out (Bazel 产物)"
        case .bazelTestlogs: return "bazel-testlogs (Bazel 产物)"
        case .cxx: return ".cxx (Android 原生产物)"
        case .externalNativeBuild: return ".externalNativeBuild (Android 原生产物)"
        case .kotlinCache: return ".kotlin (Kotlin 缓存)"
        }
    }

    public static let directoryNames: Set<String> = Set(allCases.map(\.rawValue))
}
